#!/bin/bash

# Set appropriate file permissions
chmod -R 664 ./
chmod 775 git-greenbase install run_tests

# Add symbolic link to path
sudo ln -fs "$(pwd)/git-greenbase" /usr/local/bin/git-greenbase

